### ISSUE TITLE
Update translation process

### ISSUE THREAD

**Issue by rocksdanister** [rocksdanister/lively-translations#68]
https://poeditor.com/pricing/

Has free license for opensource software, need to look into it further.

**Comment by westor7** [comment]
I don't know if you wanna look at crowdin.com either.

**Comment by bemoty** [comment]
Hi Dani, I can highly recommend using [Crowdin](https://crowdin.com/) — I've been managing and translating/proofreading multiple projects for years there and tried similar platforms like POeditor, Transifex and PhraseApp, too. IMO Crowdin is by far the best platform for crowdsourced translations out there (not only from a management perspective, but also for translators PLUS the support is amazing). Check out my profile [here](https://crowdin.com/profile/bemoty).

They also offer an open source license (wohoo!): https://crowdin.com/page/open-source-project-setup-request

If you need any help setting up / managing a project there please let me know, I would love to help! 😄

**Comment by playday3008** [comment]
https://crowdin.com is free to use, "Universe Sandbox 2" and GItLab use this site for community translations

**Comment by rocksdanister** [comment]
Project moved to:
https://crwd.in/lively-wallpaper
