### ISSUE TITLE
RESXEditor can't open English file

### ISSUE THREAD

**Issue by COMHack20** [rocksdanister/lively-translations#85]
When I try to open the "English" file, RESXEditor says there are wrong symbols and all that stuff. I want to translate Lively to Finnish, as I am finnish, so yeah.

**Comment by rocksdanister** [comment]
Working fine on my system :/

Its just a custom xml format, you can use code editors like visual studio code/sublime-text to edit it.

```xml
  <data name="txtLabelAppName" xml:space="preserve">
    <value>Lively</value>
  </data>
```
Edit the text inside `<value></value>`

**Comment by COMHack20** [comment]
[RESXEditor can't open English file · Issue #85 · rocksdanister_lively-translations ja 1 muu sivu - Profiili 1 – Microsoft​ Edge 2021-03-20 16-40-09.zip](https://github.com/rocksdanister/lively-translations/files/6175790/RESXEditor.can.t.open.English.file.Issue.85.rocksdanister_lively-translations.ja.1.muu.sivu.-.Profiili.1.Microsoft.Edge.2021-03-20.16-40-09.zip)
Dont mind it being on finnish, it says that there is an unexpected value.

**Comment by rocksdanister** [comment]
>RESXEditor can't open English file · Issue #85 · rocksdanister_lively-translations ja 1 muu sivu - Profiili 1 – Microsoft​ Edge 2021-03-20 16-40-09.zip

Why did you upload a video?

>Can I do it on Notepad++?

Not recommended.

**Comment by COMHack20** [comment]
Wanted to show you the error.

**Comment by COMHack20** [comment]
I just don't know why it works on you, but not on me. Only thing that I downloaded, is the English RESX file from the 1.0 folder. So is that even the right one?
